name: Metrics
'on':
  schedule:
    - cron: 0 * * * *
  workflow_dispatch: null
  push:
    branches:
      - master
      - main
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: '${{ secrets.METRICS_TOKEN }}'
          user: Fyko
          template: classic
          base: 'header, activity, community, repositories, metadata'
          config_timezone: America/Denver
          plugin_achievements: 'yes'
          plugin_achievements_display: detailed
          plugin_achievements_secrets: 'yes'
          plugin_achievements_threshold: C
          plugin_introduction: 'yes'
          plugin_introduction_title: 'yes'
